name: DamiBans
version: '1.0'
main: me.damian.bans.DamiBans
api-version: '1.21'
authors: [ DamianFarias ]
description: Punishment plugin
commands:
  kick:
  warn:
  warns:
  deletewarn:
    aliases: [delwarn]
  mute: