#file: noinspection YAMLSchemaValidation
name: DamiBans
version: '1.0'
main: me.damian.bans.DamiBans
api-version: '1.21'
authors: [ DamianFarias ]
depend:
  - SupremeBot
description: Punishment plugin
commands:
  kick:
  warn:
  warns:
  deletewarn:
    aliases: [delwarn]
  mute:
  unmute:
  ban:
  unban:
  punishments:
  checkplayer: